version: '3'
services:
  api:
    image: python:3.9.5
    working_dir: /code
    volumes:
      - type: bind
        source: ./api
        target: /code

  db:
    image: postgres:12.4
    environment: 
      - POSTGRES_USER=user
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"